// src/routes/saveOrder.js
//
// Handles order persistence after a successful Remita payment.
//
// Flow:
//   1. Frontend calls POST /api/checkout/save-order with { rrr, orderId, contact, shipping, items }
//   2. We call Remita's status check endpoint to verify the payment server-side
//   3. If payment is confirmed (01 = successful), we write the order + line items to Supabase
//   4. If payment is still pending (021), we save with payment_status = 'pending' (webhook will finalise)
//   5. Any other status → reject
//
// Remita webhook (POST /api/webhooks/remita) also calls persistOrder() to handle
// async confirmations without the frontend needing to poll.

import { Hono } from 'hono';
import { createSupabaseClient } from '../../lib/supabase.js';

const router = new Hono();

// ─── Remita status codes
const REMITA_STATUS = {
	SUCCESS:  '01',   // Payment successful
	PENDING:  '021',  // Awaiting confirmation
	FAILED:   '031',
	REVERSED: '04',
};

//  Remita status endpoint
const REMITA_BASE_URL = 'https://demo.remita.net/remita/exapp/api/v1/send/api/echannelsvc/';

/**
 * Fetches the current status of a Remita payment by RRR.
 * Returns the raw Remita response object.
 *
 * @param {string} rrr — Remita Retrieval Reference
 * @param {object} env — Cloudflare Worker env bindings
 */
async function checkRemitaPaymentStatus(rrr, env) {
	const hashInput = `${env.MERCHANT_ID}${rrr}${env.API_KEY}`;
	const encoder = new TextEncoder();
	const hashBuffer = await crypto.subtle.digest('SHA-512', encoder.encode(hashInput));
	const hashArray = Array.from(new Uint8Array(hashBuffer));
	const apiHash = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

	const url = `${REMITA_BASE_URL}${env.MERCHANT_ID}/${rrr}/${apiHash}/status.reg`;

	const res = await fetch(url, {
		method: 'GET',
		headers: {
			'Content-Type': 'application/json',
			'Authorization': `remitaConsumerKey=${env.MERCHANT_ID},remitaConsumerToken=${apiHash}`,
		},
	});

	if (!res.ok) {
		throw new Error(`Remita status check failed: HTTP ${res.status}`);
	}

	// Remita wraps JSON in a JSONP callback: "jsonp_cb(...)"
	const text = await res.text();
	try {
		// Strip JSONP wrapper if present
		const jsonStart = text.indexOf('{');
		const jsonEnd   = text.lastIndexOf('}');
		if (jsonStart === -1) throw new Error('No JSON in Remita response');
		return JSON.parse(text.substring(jsonStart, jsonEnd + 1));
	} catch {
		throw new Error('Could not parse Remita status response');
	}
}

//  Core order persistence
/**
 * Writes the order and its line items to Supabase.
 * Called from both the /save-order endpoint and the Remita webhook handler.
 *
 * @param {object} db            — Supabase client
 * @param {object} orderData     — validated order fields
 * @param {Array}  lineItems     — [{ variantId, quantity, price, lineTotal }]
 * @returns {{ order, error }}
 */
export async function persistOrder(db, orderData, lineItems) {
	// 1. Insert the order record
	//    The order_number is generated by the DB trigger (generate_order_number).
	const { data: order, error: orderErr } = await db
		.from('orders')
		.insert({
			// Identifiers
			user_id:          orderData.userId ?? null,
			payment_ref:      orderData.paymentRef,
			payment_method:   orderData.paymentMethod,
			payment_provider: orderData.paymentProvider,
			payment_status:   orderData.paymentStatus,

			// Financials
			subtotal:         orderData.subtotal,
			shipping_fee:     orderData.shippingFee,
			discount_amount:  orderData.discountAmount ?? 0,
			total:            orderData.total,
			currency:         'NGN',

			// Status
			status:           orderData.paymentStatus === 'paid' ? 'confirmed' : 'pending',
			paid_at:          orderData.paymentStatus === 'paid' ? new Date().toISOString() : null,

			// Shipping details
			shipping_name:    orderData.shippingName,
			shipping_phone:   orderData.shippingPhone,
			shipping_address1:orderData.shippingAddress1,
			shipping_address2:orderData.shippingAddress2 ?? null,
			shipping_city:    orderData.shippingCity,
			shipping_state:   orderData.shippingState,
			shipping_country: orderData.shippingCountry ?? 'Nigeria',

			// Optional
			notes:            orderData.notes ?? null,
			coupon_code:      orderData.couponCode ?? null,
		})
		.select('id, order_number')
		.single();

	if (orderErr) {
		console.error('[persistOrder] order insert error:', orderErr);
		return { order: null, error: orderErr.message };
	}

	// 2. Insert line items into order_items
	//    Assumes an order_items table: order_id, variant_id, quantity, unit_price, line_total
	const itemRows = lineItems.map(item => ({
		order_id:    order.id,
		variant_id:  item.variantId,
		quantity:    item.quantity,
		unit_price:  item.price,
		line_total:  item.lineTotal,
	}));

	const { error: itemsErr } = await db
		.from('order_items')
		.insert(itemRows);

	if (itemsErr) {
		console.error('[persistOrder] order_items insert error:', itemsErr);
		// Order is saved but items failed — flag for investigation, don't fail silently
		// In production you'd want an alert/dead-letter mechanism here
		return { order, error: `Order created but line items failed: ${itemsErr.message}` };
	}

	// 3. Decrement stock for each variant
	//    We use a loop here; for high volume, a Postgres RPC function is safer (atomic)
	for (const item of lineItems) {
		const { error: stockErr } = await db.rpc('decrement_variant_stock', {
			p_variant_id: item.variantId,
			p_quantity:   item.quantity,
		});
		if (stockErr) {
			// Log but don't fail the order — stock reconciliation can run separately
			console.error(`[persistOrder] stock decrement failed for variant ${item.variantId}:`, stockErr);
		}
	}

	return { order, error: null };
}


// ─── POST /api/checkout/save-order ───────────────────────────────────────────
//
// Expected body:
// {
//   rrr:           string          — Remita RRR returned by /api/checkout/init
//   contact:       { email }
//   shipping:      { firstName, lastName, address, apartment, city, state, phone, shippingMethod }
//   items:         [{ variantId, quantity }]
//   subtotal:      number          — client-supplied (we'll verify server-side via Remita status)
//   shippingFee:   number
//   total:         number
// }
//
// We re-verify everything server-side. The client values are only used to populate
// shipping fields (which Remita doesn't return). Prices come from our DB.

router.post('/', async (c) => {
	let body;
	try {
		body = await c.req.json();
	} catch {
		return c.json({ error: 'Invalid JSON body' }, 400);
	}

	const { rrr, contact, shipping, items } = body;

	// ── Input validation ────────────────────────────────────────────────────
	if (!rrr || typeof rrr !== 'string') {
		return c.json({ error: 'RRR is required' }, 400);
	}
	if (!contact?.email || !contact.email.includes('@')) {
		return c.json({ error: 'Valid email is required' }, 400);
	}
	if (!Array.isArray(items) || items.length === 0) {
		return c.json({ error: 'Cart items are required' }, 400);
	}
	if (!shipping?.firstName || !shipping?.lastName || !shipping?.address || !shipping?.city || !shipping?.state) {
		return c.json({ error: 'Complete shipping information is required' }, 400);
	}

	const db = createSupabaseClient(c.env);

	// ── Idempotency check ────────────────────────────────────────────────────
	// If an order already exists for this RRR, return it rather than inserting again.
	// This handles double-submits (user clicking twice, browser retries, etc.)
	const { data: existing } = await db
		.from('orders')
		.select('id, order_number, status, payment_status')
		.eq('payment_ref', rrr)
		.maybeSingle();

	if (existing) {
		return c.json({
			success:     true,
			orderId:     existing.id,
			orderNumber: existing.order_number,
			status:      existing.status,
			paymentStatus: existing.payment_status,
			duplicate:   true,
		});
	}

	// Verify payment with Remita
	let remitaStatus;
	try {
		remitaStatus = await checkRemitaPaymentStatus(rrr, c.env);
	} catch (err) {
		console.error('[save-order] Remita status check error:', err.message);
		return c.json({ error: 'Could not verify payment status. Please try again shortly.' }, 502);
	}

	/*
	 * Remita status response shape (varies by integration, adjust field names as needed):
	 * {
	 *   status:      '01' | '021' | '04' | ...
	 *   message:     'Payment successful' | 'Awaiting Payment' | ...
	 *   amount:      '5000.00'
	 *   RRR:         '270007351993'
	 *   orderId:     'JM_1234_ABCDEF'
	 *   ...
	 * }
	 */
	const remitaStatusCode = remitaStatus?.status ?? remitaStatus?.paymentStatus;

	// Map Remita status code to our internal payment_status
	let paymentStatus;
	if (remitaStatusCode === REMITA_STATUS.SUCCESS || remitaStatus?.message?.toLowerCase().includes('success')) {
		paymentStatus = 'paid';
	} else if (remitaStatusCode === REMITA_STATUS.PENDING || remitaStatus?.message?.toLowerCase().includes('pending') || remitaStatus?.message?.toLowerCase().includes('awaiting')) {
		// Payment initiated but not yet confirmed — save as pending, webhook will update
		paymentStatus = 'pending';
	} else {
		// Reversed, failed, or unknown — reject the order creation
		console.warn('[save-order] Payment not successful:', remitaStatus);
		return c.json({
			error:         'Payment was not successful',
			remitaStatus:  remitaStatusCode,
			remitaMessage: remitaStatus?.message,
		}, 402); // 402 Payment Required
	}

	// ── Re-fetch and validate cart items from DB ────────────────────────────
	// We NEVER trust client-submitted prices. Re-fetch from Supabase.
	const variantIds = items.map(i => i.variantId).filter(Boolean);

	const { data: variants, error: varErr } = await db
		.from('product_variants')
		.select('id, price, stock, is_active, product_id, products ( name, price )')
		.in('id', variantIds)
		.eq('is_active', true);

	if (varErr || !variants) {
		return c.json({ error: 'Could not verify cart items' }, 500);
	}

	// Build server-side line items + subtotal
	let subtotal = 0;
	const lineItems = [];

	for (const item of items) {
		const variant = variants.find(v => v.id === item.variantId);
		if (!variant) {
			return c.json({ error: `Variant ${item.variantId} not found or inactive` }, 400);
		}
		const unitPrice = Number(variant.price ?? variant.products?.price ?? 0);
		const lineTotal = unitPrice * item.quantity;
		subtotal += lineTotal;
		lineItems.push({
			variantId: item.variantId,
			quantity:  item.quantity,
			price:     unitPrice,
			lineTotal,
		});
	}

	const SHIPPING_FEES = { express: 5000, 'other-states': 8000 };
	const shippingFee   = SHIPPING_FEES[shipping.shippingMethod ?? 'express'] ?? 5000;
	const total         = subtotal + shippingFee;

	// Cross-check: the amount Remita says was paid should roughly match our total
	// (within a small tolerance for floating-point differences)
	const remitaAmount = parseFloat(remitaStatus?.amount ?? '0');
	if (paymentStatus === 'paid' && remitaAmount > 0 && Math.abs(remitaAmount - total) > 1) {
		console.error('[save-order] Amount mismatch. Expected:', total, 'Remita reports:', remitaAmount);
		// Log the mismatch but don't block — payment was confirmed by Remita
		// You may want a stricter check or alerting in production
	}

	// ── Persist the order ────────────────────────────────────────────────────
	const { order, error: saveErr } = await persistOrder(db, {
		paymentRef:       rrr,
		paymentMethod:    'remita',
		paymentProvider:  'remita',
		paymentStatus,
		subtotal,
		shippingFee,
		total,
		shippingName:     `${shipping.firstName} ${shipping.lastName}`,
		shippingPhone:    shipping.phone,
		shippingAddress1: shipping.address,
		shippingAddress2: shipping.apartment ?? null,
		shippingCity:     shipping.city,
		shippingState:    shipping.state,
		shippingCountry:  'Nigeria',
		notes:            `Customer email: ${contact.email}`,
	}, lineItems);

	if (saveErr) {
		console.error('[save-order] persistOrder error:', saveErr);
		return c.json({ error: 'Order could not be saved. Please contact support.' }, 500);
	}

	return c.json({
		success:      true,
		orderId:      order.id,
		orderNumber:  order.order_number,
		paymentStatus,
		total,
	}, 201);
});

export default router;
